Initial golang support [Very early draft, not ready for review]
eclipse/dash-licenses pull request #77
Opened 2021-06-28 19:44 UTC by AndrienkoAleksandr

Add simple go.sum file parser. Add code to find source code for golang module or package. Add code to retrive full github HASH for clearlydefined id. Let's start for now only from HASH.
Done in the frame of the H&H day.
Remaining parts described in the todos. I will handle them, when I will find free time. Also code should be covered by tests using mocks.

## Referenced issue:
I think that's a part https://github.com/eclipse/dash-licenses/issues/75

Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>

2021-09-16 02:30 UTC, waynebeaton commented
FYI, the ClearlyDefined folks are working on means of representing Go dependencies.

https://github.com/clearlydefined/service/pull/871

2021-09-16 05:02 UTC, waynebeaton commented
I poked at this a bit tonight. Based on what I think I understand from the work that our friends over at ClearlyDefined are doing, I'm thinking that we can get away with just adding an ID parser and treat a `go.sum` file as a flat file.

e.g.,

````
public class GolangIdParser implements ContentIdParser {

	private static Pattern pattern = Pattern.compile(
	// @formatter:off
			"^(?<namespace>[^/\\s]+\\/[^/\\s]+)(?:\\/(?<path>[^\\s]+))?\\s(?<version>[^\\s/]+).*$"
	// @formatter:on
	);

	@Override
	public IContentId parseId(String value) {
		Matcher matcher = pattern.matcher(value.trim());
		if (!matcher.matches())
			return null;

		String namespace = matcher.group("namespace");
		String path = matcher.group("path");
		if (path == null)
			return null;

		String version = matcher.group("version");

		return ContentId.getContentId("go", "golang", URLEncoder.encode(namespace, Charset.defaultCharset()),
				URLEncoder.encode(path, Charset.defaultCharset()), version);
	}
}
````

There are some other cases to consider. Some of the entries are missing the `path` element (which is why I made it optional in the regexp).

One of the problems is that ClearlyDefined doesn't support the go/golang type/source yet so I haven't been able to test against that (even worse, when it encounters data that it doesn't understand it times out before sending back an error message). In the meantime, we do have some go content in IPZilla that I'll update the backend script to understand so that we can at least test against that.

2021-10-19 19:48 UTC, AndrienkoAleksandr commented
@waynebeaton Hello, I recorded demo for this pull request: https://youtu.be/37B23VbYQK4 . But if I understood correctly your comment, I have to close this pr. Well, at least I shown that even such approach is working.

2021-11-24 03:24 UTC, waynebeaton requested changes
Can you please revert the changes that don't add anything (e.g., ClearlyDefinedSupport)?

After you've done that, I'll pull this into a branch and experiment with it. I'd like see if I can make it use dependency injection without directly accessing the injector (I haven't needed to do this for the other file readers yet, but it might be a good idea to hook them up to DI as well).

2021-11-24 03:24 UTC, waynebeaton commented on core/src/main/java/org/eclipse/dash/licenses/clearlydefined/ClearlyDefinedSupport.java
> +        JsonObject defJson = JsonUtils.readJson(new StringReader(response));
AFAICT this is not a material change. Can you revert it?

2021-11-24 03:24 UTC, waynebeaton commented on core/src/main/java/org/eclipse/dash/licenses/IContentId.java
> +//	boolean isSupported();
Not a material change. Please revert.

2021-11-24 03:24 UTC, waynebeaton commented on core/src/main/java/org/eclipse/dash/licenses/cli/GoSumFileReader.java
> +  public GoSumFileReader(InputStream input, HttpClientService clientService, JsoupProvider jsoupProvider) {
For consistency, this should be reworked to use the injector rather than query the injector for values.

2021-11-24 03:24 UTC, waynebeaton commented on core/src/main/java/org/eclipse/dash/licenses/cli/Main.java
> +				reader = getReader(name, injector);
We should use dependency injection rather than query the injector directly.

2021-12-14 00:01 UTC, AndrienkoAleksandr commented
@waynebeaton , sorry for long delay...

2022-02-04 22:28 UTC, waynebeaton commented
It's my turn to apologise for the long delay. 

I've pulled in the code and rebased it on HEAD. In the process, I've introduced a lot of errors in the tests that I need to work through before I figure out the next step. I'll push a branch with this pull request so we can work on it together.

2022-02-08 04:02 UTC, waynebeaton commented
I've pushed this into a branch named `initialGoLangSupport`. Let's work from there.

AFAICT, the tests are failing because the versions being returned by calls are different form what's expected. My naive assumption is that the tests are based on volatile data.

FWIW, I've verified that the author, Oleksandr, is covered by the ECA (by virtue of their employer's MCCA). Further, the contribution is smaller than 1KLOC, so no review by the IP Team is required.

I'm going to close this pull request and start poking at the implementation on this new branch.

2022-02-08 04:02 UTC, closed without merging